### ISSUE TITLE
[SKiDL BUG] unexpected log files

### ISSUE THREAD

**Issue by adamws** [xesscorp/skidl#102]
**Describe the bug**
Not necessary a bug but I think logging could get some rework, I'm not sure if [global loggers](https://github.com/xesscorp/skidl/blob/master/skidl/logger.py#L134-L140) are good approach.

1) user gets `.erc` log without calling ` ERC()`
2) there isn't obvious way to disable these logs or define different log location (or is it?)

**To Reproduce**
```
aws:skidl_test/ $ ls
test.py
aws:skidl_test/ $ cat test.py 
from skidl import *
aws:skidl_test/ $ python test.py 
aws:skidl_test/ $ ls
test.erc  test.log  test.py
aws:skidl_test/ $ python
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from skidl import *
>>> exit()
aws:skidl_test/ $ ls
__init__.erc  __init__.log  test.erc  test.log  test.py

```

**Expected behavior**
Allow caller to configure logging.

**Desktop (please complete the following information):**
 - on linux
 - Python version `Python 3.9.1`
 - SKiDL version `0.0.30`

**Comment by xesscorp** [comment]
There was a `no_files()` function added back in Feb/2020 that disables the creation of netlists, ERCs, logs and backup libraries. That's broader than what you want, but in that function there are calls to stop logging output:

```py
def no_files(circuit=default_circuit):
    """Prevent creation of output files (netlists, ERC, logs) by this Circuit object."""
    circuit.no_files = True
    erc_logger.stop_file_output()
    logger.stop_file_output()
```

You could use those to stop logging output.

Also, you could modify the `_create_logger()` function in `logger.py` to allow another directory or log file name.

Any improvements to make the logger better are always welcome!
