### ISSUE TITLE
zyc on ubuntu

### ISSUE THREAD

**Issue by eljuligallego** [xesscorp/skidl#109]
Hello,
how I have to launch zyc on ubuntu?. in one video I saw just write zyc in command line in windows will work but after install the skidl via github with commad line like proposed in zyc help [webpage](https://xess.com/skidl/docs/_site/blog/worst-part-of-skidl) the zyc command is not recognized and skidl is working perfect.
Maybe some path not configured?.

Thanks

**Comment by xesscorp** [comment]
Did you do `pip install zyc`?

**Comment by eljuligallego** [comment]
Sorry, from webpage mention before I understand zyc was included with skidl since no mention to pip intall zyc command in install instructions.

But, just run sudo pip install zyc (had to run sudo apt-get install libgtk-3-dev before) but now it freeze when installing the wxpython...(cc1plus process consumes all cpu but never ends).

Thanks for reply.

**Comment by eljuligallego** [comment]
Done, thanks.
