### ISSUE TITLE
[SKiDL BUG] Error in Jupyter Notebook: Could not load KiCad schematic library (works on terminal)

### ISSUE THREAD

**Issue by eMPee584** [xesscorp/skidl#136]
When trying to run the example code from a Jupyter Notebook, I hit this issue that even though the kicad-symbols are accessible and the path is set, skidl chokes on them:

![image](https://user-images.githubusercontent.com/1227833/136597539-fe2a399a-14e3-4322-b528-e7f2a72834ba.png)

It works in `ipython` on a terminal:
![image](https://user-images.githubusercontent.com/1227833/136597740-f5e0441b-26d6-4cdc-bb6a-cdc5cc07ed7b.png)

This is in a [rattydave/jupyterhub](https://registry.hub.docker.com/r/rattydave/jupyterhub) docker where `kicad-symbols` is installed via `apt` and `skidl` via `conda`.. what might be happening here :thinking:

**Comment by devbisme** [comment]
Seems to work for me in Jupyter. Check your `lib_search_paths` and make sure the `kicad` entry is pointing to the right directory.

![jupyter_screenshot](https://user-images.githubusercontent.com/666592/136669062-52d85e20-2ba6-400b-82c5-ba6f1d2e7760.png)
.

**Comment by eMPee584** [comment]
Aha, **thanks** for the cue 😀 .. after having a look at `lib_search_paths` code I realized setting the environment variable from inside the notebook is too late, skidl already had tried to parse it..
restarting the container so that the `/etc/profile.d/kicad-symbols_path_for_skidl.sh`I created was evaluating at Jupyter startup fixed the issue.
