### ISSUE TITLE
missing self parameter in Pin._is_attached method

### ISSUE THREAD

**Issue by wez** [xesscorp/skidl#17]
Opening this as an issue because I'm not sure that the comment I just made here will show up anywhere useful otherwise :)

https://github.com/xesscorp/skidl/commit/57c2cfd444e8707b1a718027c50b98bb4cb3f24d#commitcomment-21738990

**Comment by xesscorp** [comment]
Thanks! That was careless of me. I've made this correction in the new release I'm preparing. Should be available in a few days.
