### ISSUE TITLE
xess.lib, pic32.lib and pickit3.lib referenced in tests/intfc_brd.py not in tree

### ISSUE THREAD

**Issue by jvestman** [xesscorp/skidl#45]
xess.lib, pic32.lib and pickit3.lib referenced in tests/intfc_brd.py are not in tree, which makes tests fail.

When reference to xess.lib is changed from 'C:\xesscorp\KiCad\libraries\xess.lib' to './tests/pic32.lib' tests proceed, but fail in:

```
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/user/src/skidl/tests/intfc_brd.py", line 22, in <module>
    vreg['IN, EN'] += vusb
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'Net'
```

I have MacOs 10.14.4 and Python 3.6.1

**Comment by xesscorp** [comment]
Thanks for reporting this issue. I added these missing libs in the most recent push.
