### ISSUE TITLE
Unexpectedly long results for search

### ISSUE THREAD

**Issue by RCoeurjoly** [xesscorp/skidl#58]
Upon searching 'opamp', I get the following results, with a lot of warnings from unrelated parts.
What is this due to?
Can someone replicate this issue?
Also, it takes a lot of time to execute the search.

> python 
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import skidl
>>> from skidl import *
>>> search('opamp')
WARNING: Could not open directory ''
WARNING: Non-identical pins with the same number (6) in symbol drawing BAT54ADW
WARNING: Non-identical pins with the same number (3) in symbol drawing BAT54ADW
WARNING: Non-identical pins with the same number (3) in symbol drawing BAV99
WARNING: Non-identical pins with the same number (6) in symbol drawing Rohm_UMP11N
WARNING: Non-identical pins with the same number (3) in symbol drawing Rohm_UMP11N
WARNING: Non-identical pins with the same number (2) in symbol drawing Rohm_UMN1N
WARNING: Non-identical pins with the same number (2) in symbol drawing Rohm_UMN1N
WARNING: Non-identical pins with the same number (2) in symbol drawing Rohm_UMN1N
                                                                  WARNING: Non-identical pins with the same number (4) in symbol drawing MC3486N
WARNING: Non-identical pins with the same number (8) in symbol drawing MC3486N
WARNING: Non-identical pins with the same number (16) in symbol drawing MC3486N
WARNING: Non-identical pins with the same number (8) in symbol drawing MC3486N
WARNING: Non-identical pins with the same number (16) in symbol drawing MC3486N
WARNING: Non-identical pins with the same number (8) in symbol drawing MC3486N
WARNING: Non-identical pins with the same number (12) in symbol drawing MC3486N
WARNING: Non-identical pins with the same number (16) in symbol drawing MC3486N
WARNING: Non-identical pins with the same number (4) in symbol drawing MC3487DX
WARNING: Non-identical pins with the same number (8) in symbol drawing MC3487DX
WARNING: Non-identical pins with the same number (16) in symbol drawing MC3487DX
WARNING: Non-identical pins with the same number (8) in symbol drawing MC3487DX
WARNING: Non-identical pins with the same number (16) in symbol drawing MC3487DX
WARNING: Non-identical pins with the same number (8) in symbol drawing MC3487DX
WARNING: Non-identical pins with the same number (12) in symbol drawing MC3487DX
WARNING: Non-identical pins with the same number (16) in symbol drawing MC3487DX
WARNING: Non-identical pins with the same number (4) in symbol drawing MC3487N
WARNING: Non-identical pins with the same number (8) in symbol drawing MC3487N
WARNING: Non-identical pins with the same number (16) in symbol drawing MC3487N
WARNING: Non-identical pins with the same number (8) in symbol drawing MC3487N
WARNING: Non-identical pins with the same number (16) in symbol drawing MC3487N
WARNING: Non-identical pins with the same number (8) in symbol drawing MC3487N
WARNING: Non-identical pins with the same number (12) in symbol drawing MC3487N
WARNING: Non-identical pins with the same number (16) in symbol drawing MC3487N
WARNING: Non-identical pins with the same number (1) in symbol drawing UA9637
WARNING: Non-identical pins with the same number (4) in symbol drawing UA9637
WARNING: Non-identical pins with the same number (1) in symbol drawing UA9638CD
WARNING: Non-identical pins with the same number (4) in symbol drawing UA9638CD
WARNING: Non-identical pins with the same number (1) in symbol drawing UA9638CP
WARNING: Non-identical pins with the same number (4) in symbol drawing UA9638CP
                     WARNING: Non-identical pins with the same number (AG19) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AH23) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AJ20) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AJ22) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AJ34) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AK13) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AK14) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AK23) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AK35) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AL22) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AM14) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AM22) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AN23) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AP20) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AP22) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AR23) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AM33) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AM34) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AM36) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AN31) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AN32) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AN34) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AN35) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AN36) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AP30) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AP32) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AP33) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AP35) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AP36) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AR30) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AR31) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AR33) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AR34) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AR36) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AT30) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AT31) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AT32) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AT33) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AT34) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AT35) in symbol drawing P4080-BGA1295
WARNING: Non-identical pins with the same number (AK34) in symbol drawing P4080-BGA1295
    WARNING: Non-identical pins with the same number (29) in symbol drawing PIC16F871-IPT
    WARNING: Non-identical pins with the same number (1) in symbol drawing 74LVC2G53
WARNING: Non-identical pins with the same number (2) in symbol drawing 74LVC2G53
WARNING: Non-identical pins with the same number (5) in symbol drawing 74LVC2G53
WARNING: Non-identical pins with the same number (6) in symbol drawing 74LVC2G53
WARNING: Non-identical pins with the same number (7) in symbol drawing 74LVC2G53
WARNING: Non-identical pins with the same number (1) in symbol drawing 74LVC1G3157
WARNING: Non-identical pins with the same number (2) in symbol drawing 74LVC1G3157
WARNING: Non-identical pins with the same number (5) in symbol drawing 74LVC1G3157
WARNING: Non-identical pins with the same number (6) in symbol drawing 74LVC1G3157
Searching Analog_Switch.lib ..WARNING: Non-identical pins with the same number (1) in symbol drawing IRF6802SD
                        WARNING: Non-identical pins with the same number (1) in symbol drawing 74LS78
WARNING: Non-identical pins with the same number (5) in symbol drawing 74LS78
                                                 WARNING: Non-identical pins with the same number (7) in symbol drawing EABC80
Amplifier_Audio.lib: OPA1622 (High-Fidelity, Bipolar-Input, Audio Operational Amplifier, VSON-10)
Amplifier_Audio.lib: LM386 (Low Voltage Audio Power Amplifier, DIP-8/SOIC-8/SSOP-8)
Amplifier_Difference.lib: LM733CH (Single Differential Amplifier, TO-5-10)
Amplifier_Difference.lib: LM733CN (Single Differential Amplifier, DIP-14)
Amplifier_Instrumentation.lib: INA327 (Precision, Rail-to-Rail I/O Instrumentation Amplifier, MSOP-10 package)
Amplifier_Instrumentation.lib: INA128 (Precision, Low Power Instrumentation Amplifier G = 1 + 49.4kOhm/Rg, DIP-8/SOIC-8)
Amplifier_Instrumentation.lib: INA326 (Precision, Rail-to-Rail I/O Instrumentation Amplifier, MSOP-8 package)
Amplifier_Operational.lib: AD8603 (Zero-Drift, Precision, Low-Noise, Rail-to-Rail Output, 36-V Operational Amplifier, TSOT-23-5)
Amplifier_Operational.lib: NE5534 (Single Low-Noise Operational Amplifiers, DIP-8/SOIC-8)
Amplifier_Operational.lib: OP179GS (Single Rail-to-Rail High Output Current Operational Amplifiers, SOIC-8)
Amplifier_Operational.lib: CA3130 (4.5MHz, BiMOS Operational Amplifier with MOSFET Input/Bipolar Output, DIP-8/SOIC-8)
Amplifier_Operational.lib: THS4631DDA (Single High-voltage, High Slew Rate, Wideband, FET-input Operational Amplifier, MSOP-8)
Amplifier_Operational.lib: LMV321 (Single Low-Noise, Low Quiescent Current, Precision Operational Amplifier e-trim Series, SC-70-5)
Amplifier_Operational.lib: ADA4530-1 (Femtoampere Input Bias Current Electrometer Amplifier, SOIC-8)
Amplifier_Operational.lib: MCP603-xCH (Single 2.7V to 6.0V Single Supply CMOS Op Amps, with Chip Select, SOT-23-6)
Amplifier_Operational.lib: MCP601-xP (Rail-to-Rail Input/Output Operational Amplifier, PDIP-8)
Amplifier_Operational.lib: LTC6082xDHC (Precision Quad CMOS Rail-to-Rail Input/Output Amplifiers, DFN-16)
Amplifier_Operational.lib: LTC6362xMS8 (Precision, Low Power, Rail-to-Rail Input/Output, Differential Op Amp/SAR ADC Driver, DFN-8)
Amplifier_Operational.lib: L272M (Dual Power Operation Amplifier, DIP-8)
Amplifier_Operational.lib: MAX4238AUT (Ultra-Low Offset/Drift, Low-Noise, Precision Amplifiers, SOT-23-6)
Amplifier_Operational.lib: LM321 (Low Power Single Operational Amplifier, SOT-23-5)
Amplifier_Operational.lib: LTC6082xGN (Quad Single-Supply, Rail-to-Rail Operational Amplifier, MicroAmplifier Series, SSOP-16)
Amplifier_Operational.lib: NCS325 (Single operational amplifier, 50uV Offset, 0.25uV/C, 35uA Zero-Drift, SOT-23-5)
Amplifier_Operational.lib: LTC6081xDD (Precision Dual CMOS Rail-to-Rail Input/Output Amplifiers, DFN-10)
Amplifier_Operational.lib: LM4250 (Programmable Operational Amplifier, DIP-8/SOIC-8)
Amplifier_Operational.lib: LMH6551MM (Differential, High-Speed, Op Amp, VSSOP-8)
Amplifier_Operational.lib: OPA2333xxDRB (Dual 1.8V, microPower, CMOS Operational Amplifiers, Zero-Drift Series, SON-8)
Amplifier_Operational.lib: TSV912IQ2T (Dual rail-to-rail input/output 8 MHz operational amplifiers, DFN-8)
Amplifier_Operational.lib: LM318M (Operational Amplifier, DIP-8)
Amplifier_Operational.lib: OPA2695xD (Dual, Ultra-Wideband, Current-Feedback Operational Amplifier with Disable, SOIC-8)
Amplifier_Operational.lib: THS3491xDDA (900-MHz, 500-mA High-Power Output Current Feedback Operational Amplifier, SOIC-8)
Amplifier_Operational.lib: LMV601 (1MHz, Low-Power, General-Purpose, 2.7V Operational Amplifiers, SC-70-6)
Amplifier_Operational.lib: LTC1152 (Rail-to-Rail Input, Rail-to-Rail Output, Zero-Drift Op Amp, DIP-8, SOIC-8)
Amplifier_Operational.lib: OP279 (Dual Rail-to-Rail High Output Current Operational Amplifiers, SOIC-8/TSSOP-8)
Amplifier_Operational.lib: NCS2325D (Dual operational amplifier, 50uV Offset, 0.25uV/C, 35uA Zero-Drift, SOIC-8)
Amplifier_Operational.lib: OPA890xD (Single Low-Power, Wideband, Voltage-Feedback Operational Amplifier with Disable, SO-8)
Amplifier_Operational.lib: LTC1151CN8 (Dual Â±15V, Zero-Drift, Operational Amplifier, DIP-8)
Amplifier_Operational.lib: OPA2691-14 (Dual Wideband, Current-Feedback Operational Amplifier With Disable, SOIC-14)
Amplifier_Operational.lib: TSV524xIQ4T (Quad CMOS Rail-to-Rail Input/Output Amplifier, 1.15MHz GBP, QFN-16)
Amplifier_Operational.lib: ADA4898-2 (Dual High Voltage, Low Noise, Low Distortion, Unity-Gain Stable, High Speed Op Amp, SOIC-8-1EP)
Amplifier_Operational.lib: LMH6551MA (Differential, High-Speed, Op Amp, SOIC-8)
Amplifier_Operational.lib: OPA330xxYFF (50Î¼V V OS, 0.25Î¼V/Â°C, 35Î¼A CMOS OPERATIONAL AMPLIFIERS, ZerÃ¸-Drift Series, DSBGA)
Amplifier_Operational.lib: LM318J (Operational Amplifier, DIP-14)
Amplifier_Operational.lib: LTC1151CSW (Dual Â±15V, Zero-Drift, Operational Amplifier, SOIC-16W)
Amplifier_Operational.lib: ADA4898-1YRDZ (High Voltage, Low Noise, Low Distortion, Unity-Gain Stable, High Speed Op Amp, SOIC-8)
Amplifier_Operational.lib: MCP6L91RT-EMS (10 MHz, 850 ÂµA Op Amps, MSOP-8)
Amplifier_Operational.lib: MCP6002-xMC (1MHz, Low-Power Op Amp, DFN-8)
Amplifier_Operational.lib: LM741 (Single JFET-Input Operational Amplifiers, DIP-8/SOIC-8)
Amplifier_Operational.lib: OP179GRT (Single Rail-to-Rail High Output Current Operational Amplifiers, SOT-23-5)
Amplifier_Operational.lib: OPA355NA (200MHz, CMOS, Operational amplifier, with shutdown, SOT-23-6)
Amplifier_Operational.lib: OP249GS (Precision JFET, High Speed, Dual Operational Amplifier, SOIC-8)
Amplifier_Operational.lib: L272 (Dual Power Operation Amplifier, DIP-16)
Amplifier_Operational.lib: OPA2376xxYZD (Dual Low-Noise, Low Quiescent Current, Precision Operational Amplifier e-trim Series, DSBGA-8)
Amplifier_Operational.lib: LMH6611 (Single Supply, 345 MHz, Rail-to-Rail Output, Amplifier, TSOT-23-6)
Amplifier_Operational.lib: MCP6L91RT-EOT (Single rail-to-rail input/output 8 MHz operational amplifiers, SOT-23-5)
Amplifier_Operational.lib: NCS4325 (Quad operational amplifier, 50uV Offset, 0.25uV/C, 35uA Zero-Drift, SOIC-14)
Amplifier_Operational.lib: LM2904 (Dual rail-to-rail input/output 8 MHz operational amplifiers, MiniSO-8)
Amplifier_Operational.lib: OPA1641 (JFET input, ultralow distortion, low-noise operational amplifier, SOIC-8/VSSOP-8)
Amplifier_Operational.lib: OP07 (Single SoundPlus High Performance Audio Operational Amplifiers, DIP-8/SOIC-8)
Amplifier_Operational.lib: ADA4841-1YRJ (Low Power, Low Noise and Distorsion, Rail-to-Rail Output Amplifier, SOT-23-6)
Amplifier_Operational.lib: OPA890xDBV (Single Low-Power, Wideband, Voltage-Feedback Operational Amplifier with Disable, SOT-23-6)
Amplifier_Operational.lib: LM675 (Power Operational Amplifier, TO-220-5)
Amplifier_Operational.lib: NCS2325DM (Dual operational amplifier, 50uV Offset, 0.25uV/C, 35uA Zero-Drift, MSOP-8)
Amplifier_Operational.lib: OPA2325 (Precision, 10-MHz, Low-Noise, Low-Power, RRIO, CMOS Operational Amplifier, SOIC-8)
Amplifier_Operational.lib: MAX4238ASA (Ultra-Low Offset/Drift, Low-Noise, Precision Amplifiers, SOIC-8)
Amplifier_Operational.lib: OPA2695xRGT (Dual, Ultra-Wideband, Current-Feedback Operational Amplifier with Disable, QFN-16)
Amplifier_Operational.lib: ADA4807-2ACP (Dual Rail-to-Rail Input/Output Amplifiers, with disable, SC-70-6/SOT-23-6)
Amplifier_Operational.lib: ADA4870ARRZ (High Speed, High Voltage, 1A Output Drive Amplifier, PSOP-20)
Amplifier_Operational.lib: LM6361 (Single High Speed Operational Amplifier, DIP-8/SOIC-8)
Amplifier_Operational.lib: MCP601-xST (Single 2.7V to 6.0V Single Supply CMOS Op Amps, TSSOP-8)
Amplifier_Operational.lib: LM2902 (Quad Rail-to-rail, 20 MHz GBP, operational amplifiers, SOIC-14/TSSOP-14)
Amplifier_Operational.lib: MCP6L91T-EOT (Single rail-to-rail input/output 8 MHz operational amplifiers, SOT-23-5)
Amplifier_Operational.lib: ADA4807-1 (Single Rail-to-Rail Input/Output Amplifiers, with disable, SC-70-6/SOT-23-6)
Amplifier_Operational.lib: MCP603-xP (Single 2.7V to 6.0V Single Supply CMOS Op Amps, with Chip Select, TSSOP-8)
Amplifier_Operational.lib: OPA333xxD (Single rail-to-rail input/output 8 MHz operational amplifiers, SOIC-8)
Amplifier_Operational.lib: L272D (Dual Power Operation Amplifier, SOIC-16)
Amplifier_Operational.lib: LTC6362xDD (Precision, Low Power, Rail-to-Rail Input/Output, Differential Op Amp/SAR ADC Driver, DFN-8)
Amplifier_Video.lib: AD813 (Single Supply, Low Power, Triple Video Amplifier, DIP-14/SOIC-14)
Device.lib: Opamp_Dual_Generic (Dual operational amplifier)
Device.lib: Opamp_Quad_Generic (Quad operational amplifier)
Power_Management.lib: TSM103W (Dual Operational Amplifier and 2.5V 0.4% Voltage Reference, SOIC-8)
Power_Management.lib: TSM102 (Dual Operational Amplifier and Dual Comparator and 0.4% Voltage Reference, SOIC-16)
Simulation_SPICE.lib: OPAMP (Operational amplifier, single, node sequence=1:+ 2:- 3:OUT 4:V+ 5:V-)
pspice.lib: OPAMP (OPAmp symbol for simulation only)
>>>

**Comment by xesscorp** [comment]
The warnings are about library symbols that have more than one pin with the same pin number. I'm not sure why some symbols are designed that way, but it seems like a mistake.

The initial invocation of `search()` is slow (takes over a minute on my PC) because it's scanning in all the libraries (mostly these large FPGA libs) looking for a match with your search string. Once that's done, any other searches are fast (and the warning messages no longer appear). The initial search might be made faster (it's on my to-do list).

**Comment by xesscorp** [comment]
I pushed a change that reduced my search() time from 108s to 21s. You can try it to see if it helps you.

**Comment by xesscorp** [comment]
OK, guess we're done here.
