### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by tmladek** [xesscorp/skidl#6]
Hi, I'm installing on Arch Linux as of 2016-09-10, and first I had slight nuisances  installing:

1. Install failed on missing `future` module. No big deal, running `pip install future` fixes it, but I'd still say it should be included in `requirements.txt`

2. Install failed on missing `KISYSMOD` environment variable. I set it manually (even though I have KiCad installed) to `/usr/share/kicad/modules`, that seems to have fixed the issue.

**Comment by xesscorp** [comment]
Thanks for the error report! I think I fixed the requirements.txt file issue by having it refer to the setup.py file. And the missing KISYSMOD variable now causes a warning but no exception.

Let me know if you find anything else!
