### ISSUE TITLE
disable writing files to current directory

### ISSUE THREAD

**Issue by matthuszagh** [xesscorp/skidl#77]
Is there a way to configure skidl's behavior related to writing files to the current directory? For instance, when I run the following example
```python
from skidl.pyspice import generate_netlist, Part, gnd

vcc = Part("pyspice", "V", value=2)
r = Part("pyspice", "R", value=1e3)
gnd += r["n"], vcc["n"]
vcc["p"] += r["p"]

circ = generate_netlist()
```
I get .erc, .log, .net and _sklib.py files. I can disable the netlist and python file with tempfile and do_backup. For instance,
```python
from skidl.pyspice import generate_netlist, Part, gnd
from tempfile import mkstemp

vcc = Part("pyspice", "V", value=2)
r = Part("pyspice", "R", value=1e3)
gnd += r["n"], vcc["n"]
vcc["p"] += r["p"]

tmpf = mkstemp()
circ = generate_netlist(file_=tmpf[1], do_backup=False)
```
Is there a way to either disable the other files or write them as temp files?

**Comment by xesscorp** [comment]
I added a `no_files()` function to suppress file output of netlists, ERCs, logs, and backup libraries. Just place it at the top of your code.
