### ISSUE TITLE
skidl and kicad-3rd-party-tools on kicad-pcb.org

### ISSUE THREAD

**Issue by paulvdhoeven** [xesscorp/skidl#79]
First:
I appreciate the effort. I have not used skidl myself, but was impressed by skidl clock, and can see opportunities for this product, especially for example for fpga designs, where schematics do not have much meaning.
Also, on the kicad forum I once pointed a bind person to skidl and he seemed to be happy with it. For him it was apparently a better interface than schematics. I can only guess at his further workflow.

There are many plugins for Kicad, and only 5 (among which xesscopr/kiCost) are mentioned on:
https://www.kicad-pcb.org/external-tools/
I am of opinion that skidl also deserves a link directly on the kicad site, and at least a portion of the tools in kicad-3rd-party-tools also deserve a link there. It would benefit both KiCad and these tools to make these tools more accessible. At least a link from kicad-pcb/external-tools to the repository of the kicad-3rd-party-tools.

Some time ago I was experimenting a bit with PCB inductors as used on the one-time-key generator shown in Eevblog #1043, but it was too cumbersome in Pcbnew, partly because curved traces have not been introduced in the stable version.
![Screw_programming_EEVblog#1043](https://user-images.githubusercontent.com/48927628/75657386-60486c00-5c66-11ea-96f6-350c2db8e4ce.png)

While searching for a place to type this text, I also noticed a java application for generating such inductors. If I had knon that back then...

Has it ever been given thought to also cross-link these other tools?

**Comment by xesscorp** [comment]
With regards to listing selected entries from the 3rd-parties repo on the KiCad website, that's under the control of whoever runs their website (CERN?). They don't seem to update their website regularly and their list of external tools is pretty hidden. There isn't even a search feature on kicad-pcb.org to find these things.

The 3rd-party repo could be added to their [sites page](https://www.kicad-pcb.org/community/sites/), but that's also pretty hidden. You also have to fork their entire website, make your addition, and then submit a pull-request before they'll consider listing the site.

There is an [index post](https://forum.kicad.info/t/index-post-for-external-plugins-section/17129) on the KiCad forum that talks about various plugins. It hasn't been updated in some time and it's also not very visible.

So yeah, more plugins could be cross-linked at these other places, but it doesn't do much good if they don't update very often and aren't very visible. I hoped to step around these issues by creating the 3rd-party repo, but it hasn't really helped.
