### ISSUE TITLE
Keyword-only arguments in Package raises ValueError

### ISSUE THREAD

**Issue by voneiden** [xesscorp/skidl#91]
**Describe the bug**

Iteration of `__kwdefaults__` attempts unpacking operation. Unlike `__defaults__`, `__kwdefaults__` is a `dict`, so it iterates by default over keys rather than items. This results in 

```
File ".../venv/lib/python3.8/site-packages/skidl/Package.py", line 102, in package
    for arg_name, dflt_value in subcirc_func.__kwdefaults__:
ValueError: too many values to unpack (expected 2)
```

**To Reproduce**

Attempt to define a package with a keyword-only argument

```
@package
def foo(net, *, bar=None):
    net
```

**Expected behavior**
Expected no error.

**Desktop :**
 - OS Gentoo Linux
 - Python version 3.8.5
 - SKiDL 0.0.30

**Comment by xesscorp** [comment]
I'm closing this issue since it's fixed. It will appear in the master branch on the next release. Thanks for the help!
