### ISSUE TITLE
If ref=None part reference gets incremented twice

### ISSUE THREAD

**Issue by voneiden** [xesscorp/skidl#95]
**Describe the bug**
If `ref=None` is passed to a part, then the reference number gets incremented twice. 

1) `Part.__init__` adds itself to the circuit
2) `Circuit.add_parts` sets the part ref. Because keyword ref is None, a unique ref is generated.
3) `Part.__init__` in the very end calls setattr on remaining keywords, including ref. Since the keyword value is still None, a unique ref is generated again. Since the ref generated in step 2  above is already taken, we end up with an extra increment.

Part ref setter should perhaps free the old name, if set, before generating a new one? Or ignore None if it already has a ref?

**To Reproduce**

```
from skidl import *

r = Part('Device', 'R', ref=None)

print(r.ref)
>>> R2
```

**Expected behavior**
```>>> R1```

**Desktop (please complete the following information):**
 - OS Gentoo Linux
 - Python version 3.8.5
 - SKiDL version 0.0.30

**Comment by xesscorp** [comment]
I decided to pop the `ref=None` item from the `attribs` argument to `Part()`. That seems to solve the problem and doesn't lead to any other test failures.

BTW, is there a situation where setting `ref = None` is useful? Or is this something you just stumbled across?
